version: '3.5'

services:
  postgres:
    container_name: datareporter_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cmnxmnzzjcczjncnxcnzkncjnc}
      PGDATA: /data/postgres
    volumes:
       - data_reporter:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - data_reporter
    restart: unless-stopped

networks:
  data_reporter:
    driver: bridge

volumes:
  data_reporter:
